### PR TITLE
docs: add solana kp generation docs

### PR DESCRIPTION
**Pull request by devDesu**
Describe how to generate keypair for solana

### CODE REVIEW

**Comment by devDesu** [comment]
Close #55

**Comment by cyphersnake** [comment]
@alexeychr 
Direct task from @AlekseiSmirnov, we did not comprehend it in any way, because we do not have more details than described in the issue

**Review by cyphersnake — COMMENTED** [review]
@alexeychr Please agree with @AlekseiSmirnov  as far as it is necessary for the project, here we are powerless

**Comment by alexeychr** [comment]
@cyphersnake Slightly changed the logic: added simple instruction to readme, while moved CLI/JS example to separate doc. Please review

**Review by cyphersnake — APPROVED** [review]

**Pull request merged**
